-- Run once before first Streamlit deployment.
-- These tables are written by the app (streaming inserts + MERGE).
-- Dataform declares them as sources but never manages or overwrites them.

CREATE SCHEMA IF NOT EXISTS `bigtribebuilders.grant_helpdesk`;

CREATE TABLE IF NOT EXISTS `bigtribebuilders.grant_helpdesk.ticket_metadata` (
  content_id   STRING  NOT NULL,   -- matches content_id in grant_tickets
  status       STRING,             -- 'open' | 'in_progress' | 'answered'
  assigned_to  STRING,             -- team member full name from stg_grant_team
  updated_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `bigtribebuilders.grant_helpdesk.ticket_comments` (
  comment_id   STRING    NOT NULL, -- UUID generated by the app
  content_id   STRING    NOT NULL, -- FK → grant_tickets.content_id
  author       STRING,             -- team member full name
  body         STRING,
  created_at   TIMESTAMP
);
